### ISSUE TITLE
现在能运行吗

### ISSUE THREAD

**Issue by takumi913** [onee-io/flash-bot#1]
https://github.com/onee-io/flash-bot/blob/master/contracts/FlashBot.sol#L172 

https://github.com/onee-io/flash-bot/blob/master/contracts/FlashBot.sol#L306

我看到好几个地方都还是 TODO 状态，请问现在是能运行的吗

**Comment by onee-io** [comment]
可以运行，TODO 的是准备借用闪电贷进行无本金套利的

#executeSwap() 这个方法是完成跨 DEX 兑换，不校验是否回本

#executeArbitrageSwap() 这个方法是在上个方法的基础上，校验是否回本，没回本就 revert

上面两个方式都是需要本金的，比如：A Token -> B Token - A Token，需要现有 A Token

**Comment by takumi913** [comment]
好的，感谢回答
